######################################################
### SETUP FOR AMD GPU DOCKER IMAGE ON UBUNTU 22.04 ###
######################################################
FROM ubuntu:22.04 AS rocm

# Set arguments
ARG ROCM_VERSION=6.1.1
ARG AMDGPU_VERSION=6.1.1
ARG TORCH_VERSION=2.3.0

# Install necessary packages and add ROCm and AMDGPU repositories
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates curl gnupg sudo libelf1 libnuma-dev build-essential git vim-nox cmake-curses-gui kmod file python3 python3-pip \
    && wget https://repo.radeon.com/amdgpu-install/${AMDGPU_VERSION}/ubuntu/jammy/amdgpu-install_6.1.60101-1_all.deb \
    && apt install ./amdgpu-install_6.1.60101-1_all.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

####################################################    
########### SETUP PYTORCH AND LOCAL USER ###########
####################################################
FROM rocm AS rocm-pytorch

# Copy sudoers file for passwordless sudo
# Create rocm-user
# Set environment variables and switch to rocm-user
COPY sudo-nopasswd /etc/sudoers.d/sudo-nopasswd
RUN useradd --create-home -G sudo,video --shell /bin/bash rocm-user
USER rocm-user
WORKDIR /home/rocm-user
ENV PATH="${PATH}:/opt/rocm/bin"

# Install and setup pytorch
RUN sudo apt install python3.10 python3-pip -y \
    && pip3 install --upgrade pip wheel \
    && pip3 install torch==${TORCH_VERSION} torchaudio==${TORCH_VERSION} --index-url https://download.pytorch.org/whl/rocm${ROCM_VERSION}