services:
  tts-generation-webui:
    build:
      context: .
      dockerfile: Dockerfile-amd
    image: tts-generation-webui:rocm-5.7-pytorch-2.3.1
    restart: unless-stopped
    ports:
      - "7860:7860"
      - "3000:3000"
    container_name: tts-generation-webui
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    command: "/bin/bash"
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 8G