services:
  tts-generation-webui:
    build:
      context: .
      dockerfile: Dockerfile-amd
    image: tts-generation-webui:rocm-pytorch-6.0.2
    
    restart: unless-stopped
    ports:
      - "7860:7860"
      - "3000:3000"
    container_name: tts-generation-webui
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
