######################################################
### SETUP FOR AMD GPU DOCKER IMAGE ON UBUNTU 22.04 ###
######################################################
FROM ubuntu:22.04 AS rocm

# Set arguments
ARG ROCM_VERSION=6.0
ARG AMDGPU_VERSION=6.0
ARG TORCH_VERSION=2.3.0

# Install necessary packages and add ROCm and AMDGPU repositories
ARG APT_PREF
RUN echo "$APT_PREF" > /etc/apt/preferences.d/rocm-pin-600
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl libnuma-dev gnupg \
  && curl -sL https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add - \
  && printf "deb [arch=amd64] https://repo.radeon.com/rocm/apt/$ROCM_VERSION/ jammy main" | tee /etc/apt/sources.list.d/rocm.list \
  && printf "deb [arch=amd64] https://repo.radeon.com/amdgpu/$AMDGPU_VERSION/ubuntu jammy main" | tee /etc/apt/sources.list.d/amdgpu.list \
  && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  sudo \
  libelf1 \
  kmod \
  file \
  rocm-dev \
  build-essential && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

####################################################    
########### SETUP PYTORCH AND LOCAL USER ###########
####################################################
FROM rocm AS rocm-pytorch

# Copy sudoers file for passwordless sudo
# Create rocm-user
# Set environment variables and switch to rocm-user
COPY sudo-nopasswd /etc/sudoers.d/sudo-nopasswd
RUN useradd --create-home -G sudo,video --shell /bin/bash rocm-user
USER rocm-user
WORKDIR /home/rocm-user
ENV PATH="${PATH}:/opt/rocm/bin"

# Install python3.10 and setup pytorch
RUN sudo apt update -y \
    && sudo apt install software-properties-common -y \
    && sudo add-apt-repository ppa:deadsnakes/ppa \
    && sudo apt update -y \
    && sudo apt install python3.10 python3.10-venv python3.10-dev \
    && sudo rm /usr/bin/python3 \
    && sudo ln -s python3.10 /usr/bin/python3 \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 \
    && pip3 install --upgrade pip wheel \
    && pip3 install torch==${TORCH_VERSION} torchaudio==${TORCH_VERSION} --index-url https://download.pytorch.org/whl/rocm${ROCM_VERSION}