name: tts-generation-webui
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - pip:
    - -r requirements.txt
    - -r requirements_audiocraft_only.txt
    - -r requirements_audiocraft_deps.txt
    - -r requirements_bark_hubert_quantizer.txt
    - -r requirements_rvc.txt
    - -r requirements_styletts2.txt
    - -r requirements_vall_e.txt
    - -r requirements_maha_tts.txt
    - hydra-core==1.3.2